server:
  port: 10010
spring:
    application:
      name: miku-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**   #路由到商品微服务
    search-service: /search/** #路由到搜索微服务
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  add-host-header: true
  sensitive-headers:   #覆盖默认敏感头信息，设置为空
miku:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: Mk_TOKEN
  filter:
    allowPaths:           #-后面带字符串代表List<String>集合
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item