server:
  port: 8099
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.42.130:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.42.130
    virtual-host: /miku
    username: miku
    password: miku
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15