server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///hm49
    username: root
    password: root
  redis:
    host: 192.168.42.130
  rabbitmq:
    host: 192.168.42.130
    virtual-host: /miku
    username: miku
    password: miku
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.miku.user.pojo